<style amp-boilerplate>
  body {
    -webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;
    -moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;
    -ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;
    animation:-amp-start 8s steps(1,end) 0s 1 normal both;
  }

  amp-img {
    height: auto;
    max-width: 100%;
  }
  amp-img[height] img { height: auto; }
  img {
    height: auto;
    max-width: 100%;
  }

  @-webkit-keyframes -amp-start {
    from {
      visibility:hidden;
    }

    to {
      visibility:visible;
    }
  }

  @-moz-keyframes -amp-start {
    from {
      visibility:hidden;
    }

    to {
      visibility:visible;
    }
  }

  @-ms-keyframes -amp-start {
    from {
      visibility:hidden;
    }

    to {
      visibility:visible;
    }
  }

  @-o-keyframes -amp-start {
    from {
      visibility:hidden;
    }

    to {
      visibility:visible;
    }
  }

  @keyframes -amp-start {
    from {
      visibility:hidden;
    }

    to {
      visibility:visible;
    }
  }
</style>
<noscript>
  <style amp-boilerplate>
    body {
      -webkit-animation:none;
      -moz-animation:none;
      -ms-animation:none;
      animation:none;
    }
  </style>
</noscript>
